name: Generate Error Codes

on:
  repository_dispatch:
    types:
      - generate-errors
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Generate Golang errors
        run: go run cmd/server/main.go && go fmt ./goerrors/errors.go

      - name: Generate token
        id: errors-go-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.errors-go-token.outputs.token }}
          commit-message: ${{ github.event.client_payload.commit-message }}
          title: "Uptake new error codes"
          body: ":robot: This PR updates the error codes. Merging this PR will trigger a deployment for the Go domain."
          branch: "update-error-codes"
          team-reviewers: "api-maintainers"
