name: Generate Error Codes

on:
  repository_dispatch:
    types:
      - generate-errors
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Generate Golang errors
        run: go run generate.go && go fmt ./errors.go
        working-directory: ./go-errors

      - name: Create App Token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "chore: update error codes"
          title: "chore: update error codes"
          body: "This PR updates the error codes. Merging this PR will trigger deployments for Go and TypeScript domains."
          branch: "update-error-codes"
          team-reviewers: "server"